[package]
name = "url_shortener"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "0.8.6", features = ["macros"]}
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
